### ISSUE TITLE
[eslint-config-unity]: linting with auto-fix breaks code

### ISSUE THREAD

**Issue by TimeRaider** [auru/unity-configs#6]
You have `index.js`:
```js
function MyObj() {}

MyObj.prototype = {
    someMethod: async function () {}
};
```

You have `.eslintrc`
```json
{
  "extends": "unity"
}
```

You run:
```bash
./node_modules/.bin/eslint --ignore-path=.gitignore --fix ./index.js 
```

You get in `index.js`:
```js
export default {};

function MyObj() {}

MyObj.prototype = {
    someMethodnction() {}
};
```

**Comment by evilj0e** [comment]
Interesting bug. I'll investigate what causes that behaviour.
Thanks a lot.

**Comment by evilj0e** [comment]
Temporary fixed by overriding the `object-shorthand` rule in https://github.com/auru/unity-configs/commit/2d5966b40177f2844f8d33c5ac40f257076ebb0b

**Comment by TimeRaider** [comment]
awesome, we'll wait for `eslint` to merge fixes on their side before closing this issue

**Comment by evilj0e** [comment]
Yes, i've got the same meaning

**Comment by evilj0e** [comment]
Fixes for `eslint` have beeb merged. I think I can close this issue.
